#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Jun  5 02:07:22 2024
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MainFrame import MainFrame


class DevEnvironment(wx.App):
    def OnInit(self):
        self.fr_main_frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.fr_main_frame)
        self.fr_main_frame.Show()
        return True

# end of class DevEnvironment

if __name__ == "__main__":
    HLEKDevEnvironment = DevEnvironment(0)
    HLEKDevEnvironment.MainLoop()
